[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/*/"
  to = "/index.html"
  status = 200
